name: data-pipeline-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pyspark==3.4.1
  - matplotlib
  - pandas
  - numpy
  - kagglehub
  - notebook
  - openjdk=11
  - pip
  - pip:
      - findspark
      - pyyaml
